steps:
  - name: if1
    type: if
    config:
      condition: false

  - name: print1
    type: stdout
    inputs: 
      - if1:true
    config:
      value: True result

  - name: print2
    type: stdout
    inputs: 
      - if1:false
    config:
      value: False result