steps:
  - name: read_file
    type: file
    config:
      path: input.txt

  - name: delay1
    type: delay
    inputs: 
      - read_file
    config:
      ms: 2000

  - name: transform1
    type: uppercase
    inputs: 
      - delay1
    config:
      value: '{{ .read_file }}'

  - name: transform2
    type: map
    inputs: 
      - transform1
    config:
      fields:
        - name: first_char
          value: '{{ .transform1 }}'
          type: string
        - name: length
          value: '{{ len .transform1 }}'
          type: int

  - name: print
    type: stdout
    inputs: 
      - transform2
    config:
      value: '{{ .transform1 }}'