steps:
  - name: read_file
    type: file
    config:
      path: input.txt

  - name: transform1
    type: uppercase
    inputs: 
      - read_file
    config:
      value: '{{ .read_file }}'

  - name: print
    type: stdout
    inputs: 
      - transform1
    config:
      value: '{{ .transform1 }}'