steps:
  - name: input1
    type: map
    config:
      fields:
        - name: data
          value: [{"Codice":"1","Descrizione":"Decrizione1"}]
  - name: foreach1
    type: foreach
    inputs:
      - input1
    config:
      list: ctx.input1.data
      steps:
        - name: say_hello
          type: stdout
          config:
            value: '`Hello ${ctx.foreach.item.Codice}`'
        - name: transform1
          type: map
          config:
            fields:
             - name: code
               value: ctx.foreach.item.Codice
             - name: description
               value: ctx.foreach.item.Descrizione
        - name: print1
          type: stdout
          inputs:
            - transform1
          config:
            value: '`Transformed item: ${ctx.transform1.code} - ${ctx.transform1.description}`'
  # - name: if1
  #   type: if
  #   config:
  #     condition: false

  # - name: print1
  #   type: stdout
  #   inputs: 
  #     - if1:true
  #   config:
  #     value: True result

  # - name: print2
  #   type: stdout
  #   inputs: 
  #     - if1:false
  #   config:
  #     value: False result
